### ISSUE TITLE
unexpected keyword argument 'attn_implementation'

### ISSUE THREAD

**Issue by momandai** [microsoft/LongRoPE#7]
Traceback (most recent call last):
  File "/home/m00830934/code/LongRoPE/evolution/evaluate.py", line 110, in <module>
    main(args)
  File "/home/m00830934/code/LongRoPE/evolution/evaluate.py", line 52, in main
    model = rope.load_model(model_name_or_path=args.model, **model_args)
  File "/home/m00830934/code/LongRoPE/rope/__init__.py", line 118, in load_model
    model = model_class.from_pretrained(
  File "/home/m00830934/anaconda3/envs/LLAMA2-7B/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "/home/m00830934/anaconda3/envs/LLAMA2-7B/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3450, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
TypeError: __init__() got an unexpected keyword argument 'attn_implementation'

**Comment by Starmys** [comment]
Please update your `transformers` package and try again.
